add read me
Koda-Finance/summitswap-interface pull request #107
Opened 2022-03-14 06:52 UTC by erwin-huang

2022-03-14 12:03 UTC, LukeSamkharadze requested changes
There are lot of uncesesary info on this readme

2022-03-14 12:03 UTC, LukeSamkharadze commented on README.md
> +
Info like this shouln't be in the public projects readme. We should add these kind of info in the internal docs like https://github.com/DX-Software/docs here

2022-03-15 04:47 UTC, erwin-huang commented on README.md
> +7. Run on every change in UIKIT `yarn upgrade @koda-finance/summitswap-uikit && yarn install`
but I think we will need it on internal docs. when we are working with a branch, we will need these steps, right?

2022-03-15 11:16 UTC, LukeSamkharadze approved these changes

2022-03-15 11:16 UTC, merged