Fetch Kapex price
Koda-Finance/summitswap-interface pull request #142
Opened 2022-04-12 17:51 UTC by umaismateen

2022-04-12 22:18 UTC, omerfurkansen requested changes

2022-04-12 22:18 UTC, omerfurkansen commented on package.json
> +    "@pancakeswap/sdk": "^2.4.5",
I don't think we need to install pancakeswap/sdk after you implement the changes (removing all token files because we only need addresses), so you can remove

2022-04-12 22:18 UTC, omerfurkansen commented on package.json
> +    "@pancakeswap/sdk": "^2.4.5",
I don't think we need to install pancakeswap/sdk after you implement the changes (removing all token files because we only need addresses), so you can remove

2022-04-12 22:18 UTC, omerfurkansen commented on src/constants/abis/routerAbi.json
> +[
Actually you don't need this file because most Router.abi that you'll be seeing will have the same structure. You should be able to  use `summitswap-router.json` without any issue in this case. Give it a try😉

2022-04-12 22:18 UTC, omerfurkansen commented on src/constants/abis/routerAbi.json
> +[
Actually you don't need this file because most Router.abi that you'll be seeing will have the same structure. You should be able to  use `summitswap-router.json` without any issue in this case. Give it a try😉

2022-04-12 22:18 UTC, omerfurkansen commented on src/constants/index.ts
> +export const pancakeswapRouterV2Address = "0x10ED43C718714eb63d5aA57B78B54704E256024E"
Having constant names with upper case is better.

2022-04-12 22:18 UTC, omerfurkansen commented on src/constants/index.ts
> +export const pancakeswapRouterV2Address = "0x10ED43C718714eb63d5aA57B78B54704E256024E"
Having constant names with upper case is better.

2022-04-12 22:18 UTC, omerfurkansen commented on src/constants/tokens-pancake.ts
> +import { ChainId, Token } from "@pancakeswap/sdk";
In this case we only use Tokens file for Kapex,Wbnb and Busd route, so you can put these addresses to constants then get them instead of having this file, first double check to not duplicate them if it's already there.

2022-04-12 22:18 UTC, omerfurkansen commented on src/constants/tokens-pancake.ts
> +import { ChainId, Token } from "@pancakeswap/sdk";
In this case we only use Tokens file for Kapex,Wbnb and Busd route, so you can put these addresses to constants then get them instead of having this file, first double check to not duplicate them if it's already there.

2022-04-12 22:18 UTC, omerfurkansen commented on src/constants/tokens-pancake.ts
> +  kapex: new Token(
Only first 3 is what we need for fetching Kapex price

2022-04-12 22:18 UTC, omerfurkansen commented on src/constants/tokens-pancake.ts
> +  kapex: new Token(
Only first 3 is what we need for fetching Kapex price

2022-04-12 22:18 UTC, omerfurkansen commented on src/hooks/useGetKapexPrice.ts
> +    const web3 = new Web3('https://bsc-dataseed1.binance.org:443')
Instead using this link directly here, check if there's any constant for that, if not add it

2022-04-12 22:18 UTC, omerfurkansen commented on src/hooks/useGetKapexPrice.ts
> +    const web3 = new Web3('https://bsc-dataseed1.binance.org:443')
Instead using this link directly here, check if there's any constant for that, if not add it

2022-04-12 22:18 UTC, omerfurkansen commented on src/hooks/useGetKapexPrice.ts
> +import { mainnetTokens } from '../constants/tokens-pancake'
Not necessarily need to have all tokens, get needed token addresses from constants after adding them.

2022-04-12 22:18 UTC, omerfurkansen commented on src/hooks/useGetKapexPrice.ts
> +import { mainnetTokens } from '../constants/tokens-pancake'
Not necessarily need to have all tokens, get needed token addresses from constants after adding them.

2022-04-12 22:18 UTC, omerfurkansen commented
Also make sure all checks are successful

2022-04-13 12:54 UTC, umaismateen commented on package.json
> +    "@pancakeswap/sdk": "^2.4.5",
Removed.

2022-04-18 11:37 UTC, LukeSamkharadze requested changes

2022-04-18 11:37 UTC, LukeSamkharadze commented on src/constants/index.ts
> +
We already have this exported from `sdk` it's called `WETH`

2022-04-18 12:15 UTC, LukeSamkharadze commented on src/constants/index.ts
> +export const PANCAKESWAP_ROUTER_V2_ADDRESS = ADDITIONAL_ROUTER_ADDRESSES[0]
I think we should introduce new `env` variable for pancakeswap router specifically, otherwise changing order of the `additional_router_addresses` with mess this up

2022-04-18 12:15 UTC, LukeSamkharadze commented on src/constants/index.ts
> +
I think when we define this variable in constants, it should be more general and use current chainId instead of hardcoding

2022-04-18 12:15 UTC, LukeSamkharadze commented on src/constants/index.ts
> +
Could you refactor `BUSD` token like we have `KAPEX`? It will get get current address of `KAPEX` based on the chain

2022-04-18 13:43 UTC, LukeSamkharadze requested changes

2022-04-18 13:43 UTC, LukeSamkharadze commented on src/pages/Referral/TokenCard.tsx
> +    const tokenList: Token[] = [BUSD[CHAIN_ID], KAPEX, outputToken, rewardToken].filter(o => !!o && o !== NULL_ADDRESS);
Is this correct?

2022-04-18 13:43 UTC, LukeSamkharadze commented on src/constants/index.ts
> +export const KAPEX_TO_BUSD_ROUTE = [KAPEX.address, WETH[ChainId.MAINNET].address, BUSD.address]
Using `CHAIN_ID` constant instead of only mainnet would be better

2022-04-18 13:43 UTC, LukeSamkharadze commented on src/hooks/useGetKapexPriceData.ts
> +        setPrice("0.001") // Means it's on Testnet
Let's not display anything when on testnet, or have some kind of placeholder instead of `0.001` this may lead us to confusion

2022-04-19 11:26 UTC, LukeSamkharadze commented
@jmontanholi I think you pushed to the wrong branch

2022-04-19 20:22 UTC, LukeSamkharadze commented on package.json
> +	"dependencies": {
This is too much spaces, I think you should turn off auto formatting on save 😀

2022-04-19 20:25 UTC, jmontanholi commented on package.json
> +	"dependencies": {
Weird, I think it bugged, I changed from 4 to 2, instead, it added more spaces on the commit.

2022-04-19 20:26 UTC, jmontanholi commented on package.json
> +	"dependencies": {
can you please make a commit changing it to 2? I can't do it because locally it is 2 spaces.

2022-04-19 20:30 UTC, LukeSamkharadze commented on package.json
> +	"dependencies": {
Which IDE are you using?

2022-04-19 20:31 UTC, jmontanholi commented on package.json
> +	"dependencies": {
VSC

2022-04-19 20:34 UTC, LukeSamkharadze commented on package.json
> +	"dependencies": {
Can you try merging to develop and seeing if you see lot's of spaces?

2022-04-19 20:35 UTC, jmontanholi commented on package.json
> +	"dependencies": {
ok

2022-04-19 20:36 UTC, jmontanholi commented on package.json
> +	"dependencies": {
locally I get 2 spaces on the visualizer, but it is marking the file as 252 changes, so I'm not really sure if it is correct.

2022-04-19 20:37 UTC, LukeSamkharadze commented on package.json
> +	"dependencies": {
Even after merging to `develop`? I added some vsc configuration files

2022-04-19 20:39 UTC, jmontanholi commented on package.json
> +	"dependencies": {
![image](https://user-images.githubusercontent.com/73256642/164091638-cdf395d1-6aff-416d-a2ce-6e6d7ecd321e.png)

Visually it is 2 spaces, but what is weird is 252 changes to the file.

2022-04-19 20:41 UTC, LukeSamkharadze commented on package.json
> +	"dependencies": {
Have you tried pressing `Shift + Alt + F`?

2022-04-19 20:43 UTC, jmontanholi commented on package.json
> +	"dependencies": {
changes nothing

2022-04-19 20:44 UTC, LukeSamkharadze commented on package.json
> +	"dependencies": {
![Screen Shot 2022-04-20 at 00 44 17](https://user-images.githubusercontent.com/31849767/164092453-956bc37c-5c53-4b36-80a1-3cdf015b338a.png)

I pressed that, see no changes but saw in git

2022-04-19 20:50 UTC, jmontanholi commented on package.json
> +	"dependencies": {
Thanks for commiting the change. Now to merge we just need you and @omerfurkansen to re-review and approve the changes.

2022-04-19 21:25 UTC, LukeSamkharadze approved these changes

2022-04-19 21:26 UTC, merged