Feat/create token page
Koda-Finance/summitswap-interface pull request #149
Opened 2022-04-19 18:09 UTC by jmontanholi

## I created the page and the route `createToken`, to access, pull the changes, open the server with `yarn start` and go to `http://localhost:3000/#/createToken`
### - On this page, the user will be able to connect his wallet(at first only metamask is being used)
### - The user will be able to create his own BEP-20 token, choosing a name, symbol, decimals(default 18), and total supply.
### - Please provide info about how to use the summitswap-interface connections that already exist, I took a look at it but did not understood everything, so went on to test with metamask
------------
<img src="https://media4.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif"/>

2022-06-01 00:22 UTC, omerfurkansen commented on .env.development
> +REACT_APP_CREATE_STANDARD_TOKEN_ADDRESS = "0x7cA8d6113Abd64f520f62896480Bc2eEB1F81D2d"
You should also put these variables into production version by living them empty,
 in order to make it production ready only by adjusting the contracts addresses
 
Also these contracts are there for creating another contracts right? It’s better if we name them as CREATOR, like `REACT_APP_STANDARD_TOKEN_CREATOR_ADDRESS`, `REACT_APP_LIQUIDITY_TOKEN_CREATOR_ADDRESS`, so on

2022-06-01 00:22 UTC, omerfurkansen commented on .env.development
> +REACT_APP_CREATE_TOKEN_FEE_RECEIVER_ADDRESS = "0x1dC525231e5aC146B219f4eff5d7Ff485DcD81ed"
what is the purpose of declaring this address here since we've never used in the project

2022-06-01 00:22 UTC, omerfurkansen commented on src/components/Menu/index.tsx
> +import useTheme from '../../hooks/useTheme'
Why do we import already existing hooks in this file and we never used `useGetKodaPriceData` and `useGetKapexPriceData`, tho they don't exist on the project

2022-06-01 00:22 UTC, omerfurkansen commented on src/constants/index.ts
> +export const CREATE_STANDARD_TOKEN_ADDRESS = `${process.env.REACT_APP_CREATE_STANDARD_TOKEN_ADDRESS}`
you don't need to export this part individually
```
export const TOKEN_CREATOR_ADDRESS = {
  'STANDART_TOKEN': `${process.env.REACT_APP_STANDART_TOKEN_CREATOR_ADDRESS}`,
  'LIQUIDITY_TOKEN': `${process.env.REACT_APP_LIQUIDITY_TOKEN_CREATOR_ADDRESS}`,
  'BABY_TOKEN': `${process.env.REACT_APP_BABY_TOKEN_CREATOR_ADDRESS}`,
  'BUYBACK_TOKEN': `${process.env.REACT_APP_BUYBACK_TOKEN_CREATOR_ADDRESS}`,
}
```
we can have this part as shown above,
it'll be more readable and easily accessible

2022-06-01 00:23 UTC, omerfurkansen commented on src/hooks/useContract.ts
> +  LOCKER_ADDRESS,
These first three lines are already imported (line 5 and 25), you don't need to import them once again...
```
import { 
  LOCKER_ADDRESS, 
  REFERRAL_ADDRESS,
  TOKEN_CREATOR_ADDRESS,
} from '../constants'
```
would be enough I believe

2022-06-01 00:23 UTC, omerfurkansen commented on src/hooks/useContract.ts
> +export function useStandardTokenContract(): Contract | null {
```
export function useTokenCreatorContract(tokenType: 'STANDARD' | 'LIQUIDITY' | 'BABY' | 'BUYBACK'): Contract | null {
  let createTokenAbi
  switch(tokenType) {
    case 'STANDARD':
      createTokenAbi = CREATE_STANDARD_TOKEN_ABI
      break;
    case 'LIQUIDITY':
      createTokenAbi = CREATE_LIQUIDITY_TOKEN_ABI
      break;
    case 'BABY':
      createTokenAbi = CREATE_BABY_TOKEN_ABI
      break;
    case 'BUYBACK':
      createTokenAbi = CREATE_BUYBACK_TOKEN_ABI
      break;
  }
  return useContract(TOKEN_CREATOR_ADDRESS[tokenType], createTokenAbi)
}
```
what do you think about this?

2022-06-01 00:23 UTC, omerfurkansen commented on src/pages/App.tsx
> +                    <Route exact path="/createToken" component={CreateToken} />
Could you rename the path as `/create-token`, for consistency

2022-06-01 00:29 UTC, omerfurkansen requested changes
- We have bunch of errors from GitHub when you push your code before putting it to review I guess it's better to double check if everything is Ok
- Styling is improper at some part (SS doesn't have `;`, you have duplicate imports etc ) (please use eslint, prettier)

2022-06-01 12:21 UTC, jmontanholi commented on .env.development
> +REACT_APP_CREATE_TOKEN_FEE_RECEIVER_ADDRESS = "0x1dC525231e5aC146B219f4eff5d7Ff485DcD81ed"
Yes, I'll remove it, it is because it was used in the last version of the contracts. Thanks!

2022-06-01 12:24 UTC, jmontanholi commented on src/components/Menu/index.tsx
> +import useTheme from '../../hooks/useTheme'
I don't know really, this is not my code, I just added the ``../../`` to it

2022-06-01 12:38 UTC, jmontanholi commented
Thanks for the review Omer! I fixed the problems as you suggested!

2022-06-03 16:54 UTC, omerfurkansen commented on src/hooks/useContract.ts
> +import CREATE_STANDARD_TOKEN_ABI from '../constants/abis/createStandardToken.json';
we should delete `;`s on SummitSwap

2022-06-03 17:24 UTC, omerfurkansen commented on src/pages/CreateToken/index.tsx
> +                  Please Connect Your wallet to continue!
You can remove this title since it's obvious he needs to connect the wallet.

2022-06-15 09:00 UTC, umaismateen commented on src/constants/index.ts
> +}
Make enum for Token types.

2022-06-15 09:09 UTC, umaismateen commented on src/pages/CreateToken/standardTokenForm.tsx
> +    const factory = useTokenCreatorContract('STANDARD')
Use enum for token Type here also.

2022-06-15 09:13 UTC, umaismateen commented on src/pages/CreateToken/standardTokenForm.tsx
> +                    </Relative>
Make components reusable.

2022-06-15 09:13 UTC, umaismateen commented on src/pages/CreateToken/standardTokenForm.tsx
> +      }
Check for negative value

2022-06-15 09:24 UTC, umaismateen commented on src/pages/CreateToken/index.tsx
> +                  </select>
Use styled dropdown.

2022-06-15 14:25 UTC, umaismateen commented on src/pages/CreateToken/babyTokenForm.tsx
> +    const dividendTracker = "0x87064D365710C0C025628ed1294548FEA4f5AD67"
Add to constants file.

2022-06-15 14:36 UTC, umaismateen commented on src/pages/CreateToken/babyTokenForm.tsx
> +        errors.taxes = 'Fees need to be less than or equal to 100%'
taxes must be  <= 25%. According to the babyToken contract.

2022-06-15 14:40 UTC, umaismateen commented on src/pages/CreateToken/buybackTokenForm.tsx
> +                            </BigLabelText>
Invalid Labels.

2022-06-22 03:47 UTC, sxio reviewed
Encounter this error running this command `yarn build-test && yarn start`
<img width="1670" alt="image" src="https://user-images.githubusercontent.com/19347052/174939348-e9f1aa58-d8bc-4ace-992b-c9850250f2a4.png">

I think solving this issue will also solving the failed AWS Amplify Web Preview as well

2022-06-22 05:13 UTC, sxio reviewed
Do you think we can add a button to go back to create token page after creating a token?
somewhere on this page
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/19347052/174948671-ab3ab1dc-f5f7-4a21-b1f7-868a9f8b20ff.png">
(this is just an idea, its not on the figma design)

2022-06-22 05:13 UTC, sxio commented on src/pages/CreateToken/liquidityTokenForm.tsx
> +interface ValueErrors {
Can we use `LiquidityTokenValues` instead, so we dont need `ValueErrors` anymore?

2022-06-22 05:13 UTC, sxio commented on src/pages/CreateToken/liquidityTokenForm.tsx
> +                  { value: PANCAKESWAP_ROUTER_V2_ADDRESS, label: 'Pancakeswap Router' },
I think its better to have this into constant, and then we can use it in `setRouter` default value

2022-06-22 05:13 UTC, sxio commented on src/pages/CreateToken/index.tsx
> +                ]}
I think we can extract this into constant and use it in `setTokenType` for its default value

2022-06-22 05:13 UTC, sxio commented on src/pages/CreateToken/TokenDashboard.tsx
> +export default function TokenDashboard({ token, tokenSupply, txAddress }: Props) {
Why is this call `TokenDashboard`?

2022-06-22 05:13 UTC, sxio commented on src/pages/CreateToken/standardTokenForm.tsx
> +interface ValueErrors {
Can we use `StandardTokenValues` and remove `ValueErrors`? Both are similar

2022-06-22 05:13 UTC, sxio commented on src/pages/CreateToken/standardTokenForm.tsx
> +  const validate = (values) => {
We can specify the type for the parameter here

2022-06-22 05:14 UTC, sxio commented
Also try to solve the integration test and unit test that are failing

2022-07-05 07:01 UTC, sxio commented on src/pages/CreateToken/StandardTokenForm.tsx
> +          { value: ethers.utils.parseUnits('0.01') } // TODO:: update contract to get price from the contract
yepp, we need to get the price from contract

2022-07-05 07:45 UTC, sxio commented on src/pages/CreateToken/LiquidityTokenForm.tsx
> +          { value: ethers.utils.parseUnits('0.01') } // TODO:: update contract to get price from the contract
yepp, we need to get the price from contract (factory, cmiiw).

2022-07-05 08:17 UTC, umaismateen commented on src/pages/CreateToken/StandardTokenForm.tsx
> +                disabled={isLoading || isFailed || !formik.isValid || !formik.touched.name}
Because initially the validate function has not been called. So, there will be no errors and` formik.Valid` will be true. So we will have to check if a field has been touched or not so validate function can run.

2022-07-05 11:33 UTC, sxio commented on src/pages/CreateToken/TokenDashboard.tsx
> +            </Button>
but this is the "View Transaction" button, right?

2022-07-06 08:54 UTC, sxio commented on src/pages/CreateToken/TokenDashboard.tsx
> +            </Button>
@umaismateen

2022-07-06 09:54 UTC, sxio commented on src/pages/CreateToken/babyTokenForm.tsx
> +        errors.taxes = 'Fees need to be less than or equal to 100%'
(not related on this scope)

2022-07-06 09:54 UTC, sxio commented on src/pages/CreateToken/buybackTokenForm.tsx
> +                            </BigLabelText>
(not related on this scope)

2022-07-06 09:56 UTC, sxio approved these changes

2022-07-06 09:58 UTC, merged