Create Custom Presale.
Koda-Finance/summitswap-interface pull request #170
Opened 2022-05-29 11:40 UTC by umaismateen

2022-06-02 15:30 UTC, jmontanholi requested changes

2022-06-02 15:30 UTC, jmontanholi commented on src/pages/CustomPresale/index.tsx
> +                  message="Softcap is the Min amount of BNB that should be raised for for a Presale to be successfull."
- Please consider removing the duplicated `for`

2022-06-02 15:30 UTC, jmontanholi commented on src/pages/CustomPresale/index.tsx
> +                  message="Minimun Buy is the minimun amount of Bnb that can used to buy Tokens."
- please consider changing from `Minimun` to `minimum` This error is appearing repeatedly on the code, nothing serious of course, just typos.

2022-06-02 15:30 UTC, jmontanholi commented on src/pages/CustomPresale/index.tsx
> +                  message="If I spend 1 BNB on how many tokens will I receive? Usually this amount is lower than presale rate to allow
- This message is a bit confusing, I can't understand exactly what this rate means only with it.

2022-06-28 07:04 UTC, sxio commented on src/pages/CustomPresale/CreatePresaleForm/index.tsx
> +          values.presaleRate * values.hardcap + values.hardcap * (values.liquidity / 100) * values.listingRate * 1.025
where does `1.025` come from? shouldn't it be using feeType variable?
it user choose fee 5% then we can multiply directly with 0.05, what about the 2% BNB raised + 2% token raised ?

2022-06-28 07:18 UTC, sxio commented on src/pages/CustomPresale/index.tsx
> +  }, [presaleAddress, location])
we can combine these two into 1 useEffect right ? cmiiw

2022-06-28 07:27 UTC, sxio commented
i tried to search in the list section, after the search, i clear the input of the search, but the original list (before searching) wont come out

2022-06-28 07:29 UTC, sxio commented on src/pages/CustomPresale/PresalesList.tsx
> +const PRESALE_CARDS_PER_PAGE = 5
* this should move to presale constant
* why not make it 6 item per page ? any reason why its 5 ?

2022-06-28 07:30 UTC, sxio commented on src/pages/CustomPresale/PresalesList.tsx
> +  const [page, setPage] = React.useState(1)
we can remove `React` in `React.useState(1)`

2022-06-28 07:45 UTC, sxio commented
found this error when clicking the list button
![image](https://user-images.githubusercontent.com/19347052/176123066-b1160ad7-34ea-4502-a358-a48e493d48e1.png)

2022-06-29 05:49 UTC, sxio commented on src/pages/CustomPresale/TokenDetails.tsx
> +  let tokensForLiquidity
i think its better to use `useMemo` for these

2022-06-29 05:49 UTC, sxio commented on src/pages/CustomPresale/TokenDetails.tsx
> +    ).toFixed(2)
[not urgent] this formula is hard to read, refactoring would be nice

2022-06-29 05:49 UTC, sxio commented on src/pages/CustomPresale/PresalesList.tsx
> +const PresalesList = ({ presaleFactoryContract, account, setButtonIndex }: Props) => {
why do we need to pass `presaleFactoryContract` as property? we can just create the instance inside this component

2022-06-29 05:49 UTC, sxio commented on src/pages/CustomPresale/PresalesList.tsx
> +const PresalesList = ({ presaleFactoryContract, account, setButtonIndex }: Props) => {
why do we need to pass `account` as property? we can just import it inside the component

2022-06-29 05:49 UTC, sxio commented on src/pages/CustomPresale/PresalesList.tsx
> +  const handleChange = (event: React.ChangeEvent<unknown>, value: number) => {
ambiguous function name

2022-06-29 05:49 UTC, sxio commented on src/pages/CustomPresale/PresalesList.tsx
> +  const inputChnageHandler = async (e: React.ChangeEvent<HTMLInputElement>) => {
* typo
* rename function to a more specific name

2022-06-29 05:50 UTC, sxio commented
just created presale says "Sale ends in" on the list
<img width="362" alt="image" src="https://user-images.githubusercontent.com/19347052/176361254-f1a63577-4f8a-4c5b-90dd-765db23be8d0.png">

2022-06-29 05:54 UTC, sxio commented on src/pages/CustomPresale/Presale.tsx
> +  }, [])
i think its better to move this to utils folder, wdyt?

2022-06-29 06:29 UTC, sxio commented on src/pages/CustomPresale/Presale.tsx
> +  const isValidAdd = (add: string) => ethers.utils.isAddress(add.trim())
why creating your own method? we can just use `isAddress` directly

2022-06-29 06:31 UTC, sxio commented on src/pages/CustomPresale/Presale.tsx
> +  const [iseAccountWhitelisted, setIsAccountWhitelisted] = useState(false)
typo iseAccountWhitelisted?

2022-06-29 06:32 UTC, sxio commented on src/pages/CustomPresale/Presale.tsx
> +      const result = await presaleContract[presaleInfo?.isPresaleCancelled ? 'widhrawBNB' : 'emergencyWithdrawBNB']()
* these strings better move to constant
* typo withdraw

2022-06-29 06:33 UTC, sxio commented on src/pages/CustomPresale/Presale.tsx
> +        error: 'Withdrawl Failed.',
typo

2022-06-29 06:37 UTC, sxio commented on src/pages/CustomPresale/Presale.tsx
> +          />
* `onBuyBnbHandler` can be move inside `BuyTokens` component right?
* i think `BuyTokens` component should only handle buying token process, split up the claim component into its own component

    * `onClaimHandler` can be move inside that claim component

2022-06-29 06:38 UTC, sxio commented on src/pages/CustomPresale/Presale.tsx
> +              onPresaleCancelHandler={onPresaleCancelHandler}
methods that are exclusive for owner zone should be inside the component, doesnt make sense to put it on its parent component

2022-06-29 06:41 UTC, sxio commented on src/pages/CustomPresale/PresaleCard.tsx
> +  }, [presaleContract])
we have duplication code, one in here, and the other in `Presale.tsx`

2022-06-29 06:41 UTC, sxio commented on src/pages/CustomPresale/PresaleCard.tsx
> +  }, [])
we have duplication code, one in here, and the other in `Presale.tsx`

2022-06-29 07:04 UTC, sxio commented on src/pages/CustomPresale/PresaleCard.tsx
> +      <Text marginTop="20px">Progress ({presaleInfo?.totalBought.mul(100).div(presaleInfo.hardcap).toString()}%)</Text>
toFixed(2) ?

2022-06-29 07:06 UTC, sxio commented on src/pages/CustomPresale/PresaleCard.tsx
> +        <Text>{`${formatUnits(presaleInfo?.hardcap, 18)} BNB`}</Text>
toFixed(2)

2022-06-29 07:09 UTC, sxio commented on src/pages/CustomPresale/PresaleCard.tsx
> +        <StyledTextCard textTransform="capitalize">{checkPhase(presaleInfo).toLowerCase()}</StyledTextCard>
[not urgent] i think its better to highlight the value, not the label

2022-06-29 07:09 UTC, sxio commented on src/pages/CustomPresale/PresaleCard.tsx
> +              Sale Ends in:{' '}
what about the start ?

2022-06-29 07:22 UTC, sxio commented on src/pages/CustomPresale/PresaleDetail.tsx
> +          {' '}
why is there a space here ?

2022-06-29 07:24 UTC, sxio commented on src/pages/CustomPresale/PresaleDetail.tsx
> +            presaleInfo?.router !== ROUTER_ADDRESS
i think this should be `===` instead of `!==`

2022-06-29 07:35 UTC, sxio commented on src/pages/CustomPresale/BuyTokens.tsx
> +  }
ambiguous function name

2022-06-29 07:37 UTC, sxio commented on src/pages/CustomPresale/BuyTokens.tsx
> +          {/* <Progress primaryStep={20} /> */}
remove unuse comment

2022-06-29 07:39 UTC, sxio commented on src/pages/CustomPresale/BuyTokens.tsx
> +      </Section>
better to make another component for this

2022-06-29 07:39 UTC, sxio commented on src/pages/CustomPresale/BuyTokens.tsx
> +      )}
better to create another component for this

2022-06-30 07:23 UTC, umaismateen commented on src/pages/CustomPresale/CreatePresaleForm/index.tsx
> +        const feeTokens = values.feeType === 0 ? 0 : presaleTokenAmount * (FEE_BNB_N_TOKEN / 100)
So, there are types of fees:
1. 5% bnb raised
2. 2% bnb raised and 2% token raised

2022-06-30 08:08 UTC, umaismateen commented on src/pages/CustomPresale/Presale.tsx
> +  }, [])
I made them because the original ones will give errors if the amount sent to them is undefined, So for cleaner structure in code and to avoid checks within the components I made them.

2022-07-01 07:28 UTC, sxio commented on src/pages/CustomPresale/CreatePresaleForm/index.tsx
> +          ? 0
any reason why is this 0 ?

2022-07-01 07:36 UTC, sxio commented on src/pages/CustomPresale/CreatePresaleForm/index.tsx
> +            : RadioFieldValues.refundTypeBurn,
why do we need these validation ?

2022-07-01 07:40 UTC, sxio commented on src/pages/CustomPresale/CreatePresaleForm/index.tsx
> +        const feeTokens = values.feeType === 0 ? 0 : presaleTokenAmount * (FEE_BNB_N_TOKEN / 100)
so as you mentioned there are two types of fee, the first type is 5% bnb raised (type 0) and the second 2% bnb aised and 2% token raised (type 1), then
why on this expression `values.feeType === 0 ? 0` the fee is 0 ? it should be 5 percent right ?

2022-07-01 07:51 UTC, sxio commented on src/pages/CustomPresale/Presale.tsx
> +  }, [])
its better to use `formatUnits(amount || BigNumber.from("0"), decimals)`, because its not best practice to redefine a simple function just to validate `undefined` or not. if the library provide more than two functions then its not a good idea to redefine everything when we want to use it

2022-07-01 07:54 UTC, sxio commented on src/pages/CustomPresale/Presale.tsx
> +  }
* typo `addWhitelistAddressesChangeHanlder`
* why do you define the function here just to pass them to child component? you can just define the function directly inside the child component

2022-07-01 09:38 UTC, umaismateen commented on src/pages/CustomPresale/CreatePresaleForm/index.tsx
> +          ? 0
Because If feeType is only Bnb then we don't need any tokens for that.

2022-07-01 10:14 UTC, sxio commented
i am unable to select the fee type
<img width="330" alt="image" src="https://user-images.githubusercontent.com/19347052/176875236-3d2f9195-cab7-41f3-b146-772d1c1878be.png">

2022-07-01 11:05 UTC, sxio commented on src/pages/CustomPresale/Presale.tsx
> +              account={account}
account can just be import inside the component, didn't need to pass thru props

2022-07-05 04:24 UTC, sxio commented
<img width="145" alt="image" src="https://user-images.githubusercontent.com/19347052/177247006-c2bf4bf4-4703-4048-a188-614739f08fff.png">

found issue with the countdown where the number 1 has no unit shown, in this case it should be 1D and 1S

check this out: https://codesandbox.io/s/date-fns-tz-test-forked-6rbfs?file=/src/index.js

2022-07-06 06:52 UTC, sxio commented
Next Update:
* https://github.com/Koda-Finance/summitswap-interface/pull/170#discussion_r909273268
* https://github.com/Koda-Finance/summitswap-interface/pull/170#discussion_r909205420

2022-07-06 06:54 UTC, sxio approved these changes

2022-07-06 06:54 UTC, merged